config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get "/contact", to: "pages#contact"
  get "/about", to: "pages#about"
  get  '/signup',  to: 'users#new'
  root "pages#index" 
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :posts, only:[:create, :destroy]
  post "/like", to: "likes#create"
  delete "/unlike", to: "likes#destroy"
  post "/follow", to: "relationships#create"
  delete "/unfollow", to: "relationships#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    validates :body, length: {maximum: 255}
    validates :user_id, presence: true
    belongs_to :user
    has_one_attached :image
    has_many :likes


    default_scope -> {order "created_at DESC"}
	

	def liked?(user_id)
    	likes.where(user_id: user_id).count > 0
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    validates :follower_id, presence: true
    validates :followed_id, presence: true
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_one_attached :avatar
    has_many :posts
    has_many :likes
    has_many :relationships, foreign_key: :followed_id, dependent: :destroy
    has_many :followers, through: :relationships
    has_many :reverse_relationships, foreign_key: :follower_id, class_name: "Relationship",dependent: :destroy
    has_many :following, through: :reverse_relationships, source: :followed

    validates_presence_of :email, :username, :avatar
    validates_uniqueness_of :email, :username
    validates :password, length: {minimum: 6,maximum: 30}
    validates :username, :password, format: { with: /\A[0-9a-zA-Z_.\-]+\Z/, message: "Only alphanumeric characters, and -_."}
    validates :username, length: {maximum: 30}
	before_create {self.email = email.downcase}
    before_create {self.username = username.downcase}

    def follow(user)
        reverse_relationships.create(followed_id: user.id) unless following?(user)
    end
        
      	def unfollow(user)
    		reverse_relationships.where(followed_id: user.id).first.destroy if following?(user)
       	end
        
    	def following?(user)
    		reverse_relationships.where(followed_id: user.id).count > 0
    	end

    	def feed
    		Post.where(user_id: following_ids.append(self.id))
    	end
    
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @post_id = params[:like][:post_id]
        Like.new(user_id: current_user.id, post_id: @post_id).save
        @count= Post.find(@post_id).likes.count
        respond_to do |format|
            format.js {}    
        end
    end
    def destroy
        @post_id = params[:like][:post_id]
                Like.where(post_id: @post_id, user_id: current_user.id).first.destroy!
                @count= Post.find(@post_id).likes.count
        		respond_to do |format|
        			format.js {}
                end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if signed_in?
      @feed=current_user.feed
      @post=Post.new
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :check , only: :destroy
    def create
        @post= current_user.posts.build(post_params)
        if @post.save
            redirect_to root_path
        else
            render "pages#new"
        end
    end
    def edit
    end
    def destroy
        Post.find(params[:id]).destroy! 
        redirect_to root_path
    end
    private
    def post_params
        params.require(:post).permit(:body,:image)
    end 
    def check 
        unless current_user && Post.find(params[:id]).user_id == current_user.id
    			flash[:danger] = "Not your post!"
        		redirect_to root_path
        end
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :signed_in?
  def create
    followed_id = params[:follow][:followed_id]
    @user= User.find(followed_id)
    current_user.follow(@user)
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    followed_id = params[:follow][:followed_id]
    @user= User.find(followed_id)
    current_user.unfollow(@user)
    respond_to do |format|
      format.js {}
      end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new

end

def create
   login = params[:session][:login]
   if login.include? "@"
        user=User.find_by_email(login) 
    else 
        user=User.find_by_username(login)
    end

    if user && user.authenticate(params[:session][:password])
        sign_in user
        redirect_to user
    else
        flash[:error] = "Invaild username or email"
        render "new"
    end
end

def destroy
sign_out
redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    @users = User.all
    end
    def show
    @user = User.find(params[:id])
    end
    def new
        @user = User.new
end
    def create
        @user = User.new(user_params)
                if @user.save
                sign_in @user
        		redirect_to @user
        		else
        			render :new
        		end
    end
    def edit
        @user=User.find(params[:id])
    end
    def update
        @user= User.find(params[:id])
        if @user.update_attributes(user_params)
             redirect_to @user
        else
            render 'edit'
        end
    end
    def destroy
    end
    private
	def user_params
		params.require(:user).permit(:username, :email, :password, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
    def pretty_title(title)
        " | " + title unless title.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
    session[:user_id] = user.id
    end
    def signed_in?
        !current_user.nil?
    end
    def current_user?(user_id)
        user_id==current_user.id if current_user
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end 
    def sign_out
        session[:user_id]=nil
        @current_user=nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roflobaza
    <%= pretty_title(@title)%>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "partials/header"%>
  <div class="container">
    <%= render "partials/errors"%>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<%= form_for(:like, url: unlike_path, method: :delete, remote: true) do |f|%>
    <%= f.hidden_field :post_id, value: post_id%>
    <button type="submit">
        <i class="fa fa-heart"></i>
        </button>
        <%= count%>
    <% end%>

app/views/likes/_likes.html.erb
<div id="like-<%= post.id %>">
<% @count = post.likes.count %>
<% if post.liked?(current_user.id)%>
    <%= render "likes/like", post_id: post.id,count: @count%>
<% else %>
    <%= render "likes/unlike", post_id: post.id,count: @count%>
<%end%>

app/views/likes/_unlike.html.erb
<%= form_for(:like, url: like_path, remote: true) do |f|%>
    <%= f.hidden_field :post_id, value: post_id%>
    <button type="submit">
        <i class="fa fa-heart-o"></i>
        </button>
        <%= count%>
    <% end%>

app/views/likes/create.js.erb
$("#like-<%= @post_id %>").html("<%= escape_javascript(render('likes/like',post_id: @post_id,count: @count))%>");

app/views/likes/destroy.js.erb
$("#like-<%= @post_id %>").html("<%= escape_javascript(render('likes/unlike',post_id: @post_id,count: @count))%>");

app/views/pages/about.html.erb
<%@title = "About"%>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<%@title="Contacts"%>

<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<% @title ="Homepage"%>
<div class="container">
<% if signed_in? %>
<div class="row">
    <div class="col-md-3">
            <% if current_user.avatar.attachment%>
                <%= image_tag current_user.avatar,height: 50 %>
            <%end%>
            <h3><%= current_user.username%></h3>
            <%= form_for @post do |f|%>
            <div class="form-group">
            <%= f.text_area :body,class:"form-control"%>
            </div>
            <div class="form-group">
	        <%= f.file_field :image,class:"form-control" %>
	        </div>
            <%= f.submit :submit,class:"btn btn-primary" %> 
            <%end%>
            </div>
            <div class="col-md-9">
			    <%= render @feed %>
		    </div>
            </div>
            <% else %>
           <div class= "jumbotron">
                 <h1>Welcome to Roflobaza</h1>
            <%= link_to "Sign in", login_path, class:"btn btn-primary"%>
            <%= link_to "Register", signup_path, class:"btn btn-outline-info"%>
            </div>
            <%end%>
            </div>
    

app/views/partials/_errors.html.erb
<% unless flash.empty? %>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key%>">
			<%= value %>
		</div>
	<% end %>
<% end %> 

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a href="/"><%=image_tag("RofloBaza.png",size:"200x70") %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contact">Contact</a>
            </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <% if signed_in? %>
              <li class="nav-item"><%= link_to "Users", users_path, class:"nav-link" %></li>
              <li class="nav-item"><%= link_to "Profile", current_user, class:"nav-link" %></li>
              <li class="nav-item"><%= link_to "Settings", edit_user_path(current_user), class:"nav-link" %></li>
              <li class="nav-item"><%= link_to "logout", logout_path, method: :delete, class:"nav-link" %></li>
              <% else %>  
              <li class="nav-item"><%= link_to "Signup", signup_path , class:"nav-link" %></li>
              <li class="nav-item"><%= link_to "Login", login_path,class:"nav-link" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    
  

app/views/posts/_post.html.erb
<div class="well">
    <% if post.image.attachment%>
        <%= image_tag post.image, class:"image-fluid img-thumbnail"%>
    <%end%>
    <p><%= post.body%></p>
    <%= link_to "Delete",post, method: :delete, data: {confirm: "You sure?"} if current_user?(post.user_id) %>
    <%= render "likes/likes",post: post%>
    </div>

app/views/relationships/_follow.html.erb
<%= form_for(:follow, url: follow_path, remote: true) do |f| %>
<%= f.hidden_field :followed_id,value: user.id%>
<button class="btn btn-primary">
Follow
</button>
<% end %>

app/views/relationships/_follow_form.html.erb
<div id="follow">
    <% unless user == current_user %>
        <% if current_user.following?(user)%>
            <%= render "relationships/unfollow",user: user%>
        <% else%>
            <%= render "relationships/follow",user: user%>
        <%end%>
    <%end%>
</div>

app/views/relationships/_unfollow.html.erb
<%= form_for(:follow, url: unfollow_path,method: :delete, remote: true) do |f| %>
<%= f.hidden_field :followed_id,value: user.id%>
<button class="btn btn-danger">
Unfollow
</button>
<% end %>

app/views/relationships/create.js.erb
$("#follow").html("<%= escape_javascript(render('relationships/unfollow', user: @user))%>");

app/views/relationships/destroy.js.erb
$("#follow").html("<%= escape_javascript(render('relationships/follow', user: @user))%>");

app/views/users/edit.html.erb
<%@title="Update Profile"%>
<h1>Update Your Profile</h1>
<%= form_for(@user) do |f| %>

<% if @user.errors %>
		<ul>
			<% @user.errors.full_messages.each do |m|%>
				<li><%= m %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.text_field :username, placeholder: "username" %>
	<%= f.text_field :email, placeholder: "email" %>
	<%= f.password_field :password, placeholder: "password" %>
	<%= f.file_field :avatar %>
	<%= f.submit :submit %>
<% end %>

app/views/users/index.html.erb
<% @title="Users" %>
<ul>
    <% @users.each do |user|%>
        <li><%= link_to user.username, "/users/#{user.id}" %></li>
        <%end%>
</ul>
            

app/views/users/new.html.erb
<%@title="Signup"%>



<div class="row">
    <div class="col-md-6 offset-md-3">  
		<h1>Register</h1>
<%= form_for @user do |f| %>
	<% if @user.errors %>
		<ul>
			<% @user.errors.full_messages.each do |m|%>
				<li><%= m %></li>
			<% end %>
		</ul>
	<% end %>
	<div class="form-group">
		<%= f.text_field :username, placeholder: "username",class:"form-control" %>
	</div>
	<div class="form-group">
		<%= f.text_field :email, placeholder: "email",class:"form-control" %>
	</div>
	<div class="form-group">
		<%= f.password_field :password, placeholder: "password",class:"form-control" %>
	</div>
	<div class="form-group">
		<%= f.file_field :avatar,class:"form-control" %>
	</div>
		<%= f.submit :submit,class:"btn btn-primary" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<% @title="Your Profile"%>

  <div class="row">
	  <div class="col-md-3">
      <h2><%= @user.username %></h2>
        <h3><%= @user.email %></h3>
      <% unless @user.avatar.attachment.nil? %>
        <%= image_tag @user.avatar,class: "img-fluid" %>
      <% else %>
        <img src="https://www.bsn.eu/wp-content/uploads/2016/12/user-icon-image-placeholder-300-grey.jpg",class="img-fluid">
      <% end %> 
      <%= render "relationships/follow_form", user: @user%>
  </div>
    <div class="col-md-9">
    <%=render @user.posts %>
    </div>
  </div>